### ISSUE TITLE
How to get the swipe animation programmatically?

### ISSUE THREAD

**Issue by ThibaultKlein** [prolificinteractive/Caishen#55]
Hi,

I noticed that when you entered a valid credit card number, exp date and CVV and you go back to the credit card field, exp date and CVV fields disappear. One way to see them again is to swipe in the text field, but I'd like to programmatically trigger the same animation when the card number text field becomes first responder. Any ideas on how to do that?

Thanks!

**Comment by DannyVancura** [comment]
Hi,
these methods are currently internal to Caishen.
You can, however, access them by calling the selectors directly via
```swift
cardTextField.performSelector(Selector("moveNumberFieldLeft"))
```
```swift
cardTextField.performSelector(Selector("moveNumberFieldLeftAnimated"))
```
```swift
cardTextField.performSelector(Selector("moveNumberFieldRight"))
```
```swift
cardTextField.performSelector(Selector("moveNumberFieldRightAnimated"))
```

**Note**: The `moveNumberFieldLeft` and `moveNumberFieldLeftAnimated` functions will only perform the change if the card number has been entered and is valid.

**Comment by ThibaultKlein** [comment]
Hi @DannyVancura,

`Selector` is deprecated with Xcode 7.3, and if I use the new `#selector` it requires to provide the function instead of a string, but because it's internal I can't access it.

**Comment by DannyVancura** [comment]
@ThibaultKlein Thanks for pointing this out. I created a pull request to make these methods public. I also renamed them to move card number `out` or `in`.

This PR will give you access to `moveCardNumberOut`, `moveCardNumberOutAnimated`, `moveCardNumberIn` and `moveCardNumberInAnimated`. 

As before: `moveCardNumberOut` and `moveCardNumberOutAnimated` will do nothing as long as the card number is not valid, simply because the `moveCardNumberOut` animation is supposed to show the last four digits of the card number, which only makes sense for a complete card number.
